[agent]
  interval = "10s"
  flush_interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  hostname = "cms-vm"
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "telegraf"
  skip_database_creation = false

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.processes]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs", "nsfs", "proc", "sysfs"]

[[inputs.diskio]]

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  perdevice = false
  perdevice_include = []
  total = true
  total_include = ["cpu", "blkio", "network"]
  docker_label_include = ["com.docker.compose.service"]

[[inputs.nginx]]
  urls = ["http://nginx/nginx_status"]
  response_timeout = "5s"

[[inputs.tail]]
  name_override = "nginx_access"
  files = ["/var/log/nginx/access.json"]
  from_beginning = false
  watch_method = "poll"
  data_format = "json"
  tag_keys = ["status", "method"]

[[inputs.phpfpm]]
  urls = ["fcgi://wordpress:9000/status"]
  timeout = "5s"

[[inputs.mysql]]
  servers = ["telegraf:${MYSQL_TELEGRAF_PASSWORD}@tcp(db:3306)/?tls=false"]
  gather_global_variables = true
  gather_process_list = false
  gather_innodb_metrics = true
  gather_slave_status = false

[[inputs.http_response]]
  urls = ["http://nginx/", "http://nginx/wp-login.php"]
  method = "GET"
  response_timeout = "10s"
  follow_redirects = true
  response_status_code = 200
